// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebPayments.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class ContactDetails
    {
        /// <summary>
        /// Initializes a new instance of the ContactDetails class.
        /// </summary>
        public ContactDetails() { }

        /// <summary>
        /// Initializes a new instance of the ContactDetails class.
        /// </summary>
        public ContactDetails(string id = default(string), string emailAddress = default(string), string phoneNumber = default(string), AddressDetails addressInfo = default(AddressDetails))
        {
            Id = id;
            EmailAddress = emailAddress;
            PhoneNumber = phoneNumber;
            AddressInfo = addressInfo;
        }

        /// <summary>
        /// A  that contains the identifier that uniquely idenfies this
        /// information in the datastore.
        /// It can be  for a new entrty. If it is provided, rest
        /// of the information is not required
        /// unless it is an update.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// A  that contains the profile email address.
        /// </summary>
        [JsonProperty(PropertyName = "EmailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// A  that contains the phone number asociated with this profile.
        /// </summary>
        [JsonProperty(PropertyName = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// A  that contains the user's address associated with this profile.
        /// </summary>
        [JsonProperty(PropertyName = "AddressInfo")]
        public AddressDetails AddressInfo { get; set; }

    }
}
