// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebPayments.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class AddPaymentProfileAccountRequest
    {
        /// <summary>
        /// Initializes a new instance of the AddPaymentProfileAccountRequest
        /// class.
        /// </summary>
        public AddPaymentProfileAccountRequest() { }

        /// <summary>
        /// Initializes a new instance of the AddPaymentProfileAccountRequest
        /// class.
        /// </summary>
        public AddPaymentProfileAccountRequest(string transactionIdentifier = default(string), string accountType = default(string), string cardType = default(string), string last4Digits = default(string), string expirationMonth = default(string), string expirationYear = default(string), int? profileType = default(int?))
        {
            TransactionIdentifier = transactionIdentifier;
            AccountType = accountType;
            CardType = cardType;
            Last4Digits = last4Digits;
            ExpirationMonth = expirationMonth;
            ExpirationYear = expirationYear;
            ProfileType = profileType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TransactionIdentifier")]
        public string TransactionIdentifier { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountType")]
        public string AccountType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CardType")]
        public string CardType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Last4Digits")]
        public string Last4Digits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpirationMonth")]
        public string ExpirationMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpirationYear")]
        public string ExpirationYear { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProfileType")]
        public int? ProfileType { get; set; }

    }
}
