// Code generated by Microsoft (R) AutoRest Code Generator 0.14.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace WebPayments.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class PCIFormSettings
    {
        /// <summary>
        /// Initializes a new instance of the PCIFormSettings class.
        /// </summary>
        public PCIFormSettings() { }

        /// <summary>
        /// Initializes a new instance of the PCIFormSettings class.
        /// </summary>
        public PCIFormSettings(string profileType = default(string), string supportedCardTypes = default(string), bool? retrieveNonPCIData = default(bool?))
        {
            ProfileType = profileType;
            SupportedCardTypes = supportedCardTypes;
            RetrieveNonPCIData = retrieveNonPCIData;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProfileType")]
        public string ProfileType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SupportedCardTypes")]
        public string SupportedCardTypes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "RetrieveNonPCIData")]
        public bool? RetrieveNonPCIData { get; set; }

    }
}
